### ISSUE TITLE
Change the default drawable?

### ISSUE THREAD

**Issue by Alextorres950325** [aliHafizji/CreditCardEditText#3]
It's possible change the default drawable, to my custom image?
i use the .setNoMatchFoundDrawable, but the icon only change to after edtitext has focus.

**Comment by aliHafizji** [comment]
Hi Alex. 
Thanks for reporting the bug. I've fixed it and it should be available as an update through maven.

Here is the release incase you're manually adding the files: https://github.com/aliHafizji/CreditCardEditText/releases/tag/2.0
