### ISSUE TITLE
Can you show icons for rupay cards

### ISSUE THREAD

**Issue by sujayabraham** [aliHafizji/CreditCardEditText#4]
rupay: [
        {length: [16], prefixes: ['6061', '6062', '6063', '6064', '6065', '6066', '6067', '6068', '6069', '607', '608'], skip_luhn: true}
    ]

**Comment by aliHafizji** [comment]
Hi Sujay,
There are a lot of different types of cards. The library supports detection of all types as long as you provide a regex. As an example I've provided the regex strings for visa, mastercard and amex. But the same can be done for rupay. You will need to provide an icon for rupay and the regex and the library will do the rest for you.
