### ISSUE TITLE
How to change separator from "-" to " "? 

### ISSUE THREAD

**Issue by mr-kamran-ali** [aliHafizji/CreditCardEditText#5]
I cant find any way to do it, except regex. there should be arguments method to do this easily in xml. 
Please developer its a requested feature.

**Comment by hendrawd** [comment]
I think you can't do that right now, as the variable that contains the separator character as in 
https://github.com/aliHafizji/CreditCardEditText/blob/master/library/src/main/java/com/alihafizji/library/CreditCardEditText.java#L16 
is a final(immutable)

**Comment by hendrawd** [comment]
I could do a pull refresh to add this feature if you want, but it will takes some time because of my workload

**Comment by aliHafizji** [comment]
Please use the latest version of the library. `3.0.0`

You can change the separator using an attribute in the layout.

For example:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    tools:context="com.alihafizji.MainActivity$PlaceholderFragment">

    <com.alihafizji.library.CreditCardEditText
        android:id="@+id/textview_credit_card"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="textNoSuggestions"
        custom:separator="-"
        android:hint="@string/enter_card_number" />

</RelativeLayout>```
