### ISSUE TITLE
Change the logo of mastercard, visa etc. ?

### ISSUE THREAD

**Issue by omralcrt** [aliHafizji/CreditCardEditText#6]
Can there any way to change the logo of mastercard? Because I use white background and logos can't be seen.

Thanks for library

**Comment by aliHafizji** [comment]
@omralcrt Take a look at the `CreditCartEditTextInterface`. If you implement that interface and provide a list of `CreditCard` objects you can provide your drawable with the regex to use.

Maybe Use the same patterns that the `CreditCardPatterns` object returns with your drawables.
